cup_seo:
    resource: "@CupSeoBundle/Resources/config/routing.yml"
    prefix:   /

cup_security:
    resource: "@CupSecurityBundle/Resources/config/routing.yml"
    prefix:   /

cup_site_management:
    resource: "@CupSiteManagementBundle/Resources/config/routing.yml"
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
_security_check:
    path:  /{_locale}/login_check
_security_logout:
    path:  /{_locale}/logout
