<?php

namespace Cup\SiteManagementBundle\Repository;

/**
 * DeliveryPartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryPartnerRepository extends \Doctrine\ORM\EntityRepository
{
}
