<?php

namespace Cup\SiteManagementBundle\Repository;

/**
 * DeliveryCustomerDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryCustomerDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
