<?php

namespace Cup\SiteManagementBundle\Repository;

/**
 * IncomeGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
